spring.application.name=API

server.port=8000

logging.level.org.springframework.security=TRACE

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/reports-realm
spring.security.oauth2.resourceserver.jwt.roles-claim-name=realm_access.roles
spring.security.oauth2.resourceserver.jwt.role-prefix=ROLE_